# Default values for mariadb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mariadb
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  port: 3306
  targetPort: 3306

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
  - name: mariadb-volume
    persistentVolumeClaim:
      claimName: mariadb-pvc

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: mariadb-volume
    mountPath: "/var/lib/mysql"

secret:
  data:
    MARIADB_ROOT_PASSWORD: U2VjcmV0Um9vdA==
    MARIADB_USER: c29saWRpbnZvaWNl
    MARIADB_PASSWORD: U2VjcmV0U29saWRpbnZvaWNl
configMap:
  data:
    MARIADB_DATABASE: solidinvoice

pvc:
  storageClassName: csi-cinder-high-speed
  requestStorage: "1Gi"
