ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: k8slive-solidinvoice-zerofiltre-ingress-cert
      hosts:
        - k8slive.solidinvoice.zerofiltre.tech
  hosts:
    - host: k8slive.solidinvoice.zerofiltre.tech
      paths:
        - path: /
          pathType: Prefix      

image:
  repository: solidinvoice/solidinvoice

resources: 
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 250m
    memory: 200Mi


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 100
  targetMemoryUtilizationPercentage: 50